apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
  labels:
    app: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: ghcr.io/digininja/dvwa:latest
        env:
        - name: DB_SERVER
          value: db
        ports:
        - containerPort: 80
